name: auto-build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * 0'

jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: github checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          ./blocklist-build.sh

      - name: switch branch
        run: |
          git checkout -b release
          rm -rf ./.github ./readme.md ./blocklist-build.sh

      - name: push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'auto build'
          git push -f origin release
